before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
build:
  main: ./btget
  goos:
    - linux
  goarch:
    - amd64
archives:
 - 
  builds:
  - default
  wrap_in_directory: true
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'SHA256SUMS'
snapshot:
  name_template: "{{ .Tag }}-next"
